runtime: nodejs12
service: tc-geography-mngr
env_variables:
    PORT: 8083
    apiPath: ''
    databaseHost: '34.134.59.167'
    databasePass: 'root'
    databasePort: '3306'
    databaseUser: 'root'
    databesePoolAcquiere: '30000'
    databesePoolIdle:  '10000'
    databesePoolMax:  '7'
    databesePoolMin: '0'
    logSentenceSQL: true